import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, Copy, FileText, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { PageHeader } from "@/components/page-header";
import { DemoBadge, RagBadge } from "@/components/status";
import {
  assessment,
  frameworks,
  frameworkStats,
  gateConditions,
  overallCompliance,
  redRisks,
  riskScore,
  statusCounts,
  requirements,
} from "@/lib/services/governance-service";
import { useDemo } from "@/lib/store";

export const Route = createFileRoute("/executive-summary")({
  head: () => ({
    meta: [
      { title: "Executive Summary — NGET AI Governance Assurance POC" },
      { name: "description", content: "Mock one-click executive summary generation for Assessment #001. POC demo mode." },
      { property: "og:title", content: "Executive Summary — NGET AI Governance Assurance POC" },
      { property: "og:description", content: "Mock one-click executive summary generation for Assessment #001." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: ExecutiveSummaryPage,
});

const GEN_STEPS = [
  "Collating assessment verdict and KPIs…",
  "Summarising framework posture…",
  "Condensing red risks and conditions…",
  "Drafting steering-group narrative…",
];

function ExecutiveSummaryPage() {
  const { summaryGenerated, generateSummary, personaLabel } = useDemo();
  const [phase, setPhase] = useState<-1 | number>(summaryGenerated > 0 ? GEN_STEPS.length : -1);
  const generated = phase === GEN_STEPS.length;

  useEffect(() => {
    if (phase < 0 || phase >= GEN_STEPS.length) return;
    const t = window.setTimeout(() => setPhase((p) => p + 1), 800);
    return () => window.clearTimeout(t);
  }, [phase]);

  const counts = statusCounts(requirements);

  const summaryText = `NGET AI Governance Assurance — Executive Summary (POC DEMO)
${assessment.project} / ${assessment.programme} / ${assessment.gate} / ${assessment.label}
Verdict: CONDITIONALLY READY — ${overallCompliance}% weighted compliance across 94 requirements (${counts.compliant} met, ${counts.partial} partial, ${counts.gap} gaps). ${redRisks.length} red risks require treatment; four conditions precedent apply before gate submission. Generated for steering-group review.`;

  return (
    <div className="mx-auto max-w-[900px]">
      <PageHeader
        breadcrumbs={[{ label: "Dashboard", to: "/" }, { label: "Executive Summary" }]}
        title="Executive summary"
        subtitle="One-click steering-group summary of Assessment #001. Content is mock-generated and labelled POC DEMO."
        actions={<DemoBadge />}
      />

      {!generated ? (
        <div className="rounded-xl border border-border bg-card p-10 text-center">
          <FileText className="mx-auto size-10 text-muted-foreground" />
          <h2 className="mt-3 text-lg font-semibold text-foreground">
            Generate the executive summary
          </h2>
          <p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">
            Simulated generation from the Assessment #001 result set. No AI is actually called in
            this POC.
          </p>
          {phase === -1 ? (
            <button
              onClick={() => {
                setPhase(0);
                generateSummary();
              }}
              className="mt-5 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
            >
              <Sparkles className="size-4" /> Generate summary
            </button>
          ) : (
            <div className="mx-auto mt-6 max-w-sm space-y-2 text-left">
              {GEN_STEPS.map((s, i) => (
                <div key={s} className="flex items-center gap-2 text-sm">
                  {i < phase ? (
                    <Check className="size-4 text-success" />
                  ) : i === phase ? (
                    <Loader2 className="size-4 animate-spin text-primary" />
                  ) : (
                    <span className="size-4 rounded-full border border-border" />
                  )}
                  <span className={i <= phase ? "text-foreground" : "text-muted-foreground"}>
                    {s}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      ) : (
        <>
          <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
            <span className="text-xs text-muted-foreground">
              Generated by {personaLabel} · mock content · draft for human sign-off (APR-003)
            </span>
            <div className="flex gap-2">
              <button
                onClick={() => {
                  navigator.clipboard?.writeText(summaryText).catch(() => {});
                  toast.success("Summary copied to clipboard");
                }}
                className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-foreground hover:bg-muted"
              >
                <Copy className="size-3.5" /> Copy
              </button>
              <button
                onClick={() => {
                  setPhase(0);
                  generateSummary();
                }}
                className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-1.5 text-xs font-medium text-foreground hover:bg-muted"
              >
                <RefreshCw className="size-3.5" /> Regenerate
              </button>
            </div>
          </div>

          <article className="rounded-xl border border-border bg-card">
            <header className="border-b border-border p-6">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <h2 className="text-xl font-bold text-foreground">
                    {assessment.project} — {assessment.gate} Governance Summary
                  </h2>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {assessment.programme} · {assessment.label} · {assessment.completedAt}
                  </p>
                </div>
                <RagBadge color="amber" label="Conditionally ready" />
              </div>
            </header>

            <div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4">
              {[
                ["Compliance", `${overallCompliance}%`],
                ["Requirements", `${counts.compliant}/${requirements.length} met`],
                ["Open risks", `18 (${redRisks.length} red)`],
                ["Conditions", "4 precedent"],
              ].map(([label, value]) => (
                <div key={label} className="bg-card p-4">
                  <div className="text-xl font-bold text-foreground">{value}</div>
                  <div className="text-[11px] text-muted-foreground">{label}</div>
                </div>
              ))}
            </div>

            <div className="space-y-6 p-6">
              <section>
                <h3 className="mb-2 text-sm font-semibold text-foreground">Position</h3>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  The platform is broadly well-engineered: availability, response time, EU hosting
                  and SSO/MFA controls are evidenced and operating. However, {counts.gap}{" "}
                  requirement gaps concentrate in security fundamentals — encryption scope, key
                  custody, session control and penetration-test remediation — and in data-protection
                  hygiene for non-production environments.
                </p>
              </section>
              <section>
                <h3 className="mb-2 text-sm font-semibold text-foreground">Framework posture</h3>
                <ul className="space-y-1.5">
                  {frameworks.map((f) => {
                    const s = frameworkStats(f.id);
                    return (
                      <li key={f.id} className="flex items-center gap-3 text-sm">
                        <span className="w-28 font-mono text-xs text-muted-foreground">{f.code}</span>
                        <div className="h-2 flex-1 overflow-hidden rounded-full bg-muted">
                          <div
                            className={
                              s.rag === "green" ? "h-full bg-success" : s.rag === "amber" ? "h-full bg-warning" : "h-full bg-destructive"
                            }
                            style={{ width: `${s.compliance}%` }}
                          />
                        </div>
                        <span className="w-10 text-right font-mono text-xs">{s.compliance}%</span>
                      </li>
                    );
                  })}
                </ul>
              </section>
              <section>
                <h3 className="mb-2 text-sm font-semibold text-foreground">
                  Decisions needed from the steering group
                </h3>
                <ol className="list-decimal space-y-1.5 pl-5 text-sm text-muted-foreground">
                  <li>
                    Approve conditional Stage Gate A readiness with the four conditions precedent
                    formally tracked (APR-001).
                  </li>
                  <li>
                    Fund the red-risk treatment plan: highest scores are archive encryption
                    (RSK-001, {redRisks.length > 0 ? riskScore(redRisks[0]!) : 20}) and overdue
                    pen-test remediation (RSK-006, 16).
                  </li>
                  <li>
                    Direct completion of the DPIA addendum and non-prod data masking before gate
                    submission (COND-3).
                  </li>
                </ol>
              </section>
              <section>
                <h3 className="mb-2 text-sm font-semibold text-foreground">Conditions precedent</h3>
                <ul className="space-y-1.5">
                  {gateConditions.map((c) => (
                    <li key={c.id} className="text-sm text-muted-foreground">
                      <span className="font-mono text-xs text-foreground">{c.id}</span> — {c.title}.{" "}
                      {c.detail}
                    </li>
                  ))}
                </ul>
              </section>
            </div>

            <footer className="flex flex-wrap items-center justify-between gap-2 border-t border-border p-4">
              <span className="text-[11px] text-muted-foreground">
                Simulated AI output · POC DEMO MODE · not for distribution
              </span>
              <Link
                to="/approvals"
                className="inline-flex items-center gap-1.5 rounded-md bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:bg-primary/90"
              >
                Route for sign-off (APR-003)
              </Link>
            </footer>
          </article>
        </>
      )}
    </div>
  );
}
