/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as FutureRouteImport } from './routes/future'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as AssessmentsAssessmentIdRouteImport } from './routes/assessments.$assessmentId'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as FrameworksIndexRouteImport } from './routes/frameworks.index'
import { Route as FrameworksFrameworkIdRouteImport } from './routes/frameworks.$frameworkId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdRouteImport.update({
  id: '/assessments/$assessmentId',
  path: '/assessments/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIndexRoute = FrameworksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrameworksRoute,
} as any)
const FrameworksFrameworkIdRoute = FrameworksFrameworkIdRouteImport.update({
  id: '/$frameworkId',
  path: '/$frameworkId',
  getParentRoute: () => FrameworksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/findings': typeof FindingsRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/future': typeof FutureRoute
  '/settings': typeof SettingsRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/frameworks/$frameworkId': typeof FrameworksFrameworkIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/findings': typeof FindingsRoute
  '/future': typeof FutureRoute
  '/settings': typeof SettingsRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/frameworks/$frameworkId': typeof FrameworksFrameworkIdRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/frameworks': typeof FrameworksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/findings': typeof FindingsRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/future': typeof FutureRoute
  '/settings': typeof SettingsRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/frameworks/$frameworkId': typeof FrameworksFrameworkIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/findings'
    | '/frameworks'
    | '/future'
    | '/settings'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/frameworks/$frameworkId'
    | '/assessments/'
    | '/frameworks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/findings'
    | '/future'
    | '/settings'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/frameworks/$frameworkId'
    | '/assessments'
    | '/frameworks'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/findings'
    | '/frameworks'
    | '/future'
    | '/settings'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/frameworks/$frameworkId'
    | '/assessments/'
    | '/frameworks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  FindingsRoute: typeof FindingsRoute
  FrameworksRoute: typeof FrameworksRouteWithChildren
  FutureRoute: typeof FutureRoute
  SettingsRoute: typeof SettingsRoute
  AssessmentsAssessmentIdRoute: typeof AssessmentsAssessmentIdRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/': {
      id: '/frameworks/'
      path: '/'
      fullPath: '/frameworks/'
      preLoaderRoute: typeof FrameworksIndexRouteImport
      parentRoute: typeof FrameworksRoute
    }
    '/frameworks/$frameworkId': {
      id: '/frameworks/$frameworkId'
      path: '/$frameworkId'
      fullPath: '/frameworks/$frameworkId'
      preLoaderRoute: typeof FrameworksFrameworkIdRouteImport
      parentRoute: typeof FrameworksRoute
    }
  }
}

interface FrameworksRouteChildren {
  FrameworksFrameworkIdRoute: typeof FrameworksFrameworkIdRoute
  FrameworksIndexRoute: typeof FrameworksIndexRoute
}

const FrameworksRouteChildren: FrameworksRouteChildren = {
  FrameworksFrameworkIdRoute: FrameworksFrameworkIdRoute,
  FrameworksIndexRoute: FrameworksIndexRoute,
}

const FrameworksRouteWithChildren = FrameworksRoute._addFileChildren(
  FrameworksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  FindingsRoute: FindingsRoute,
  FrameworksRoute: FrameworksRouteWithChildren,
  FutureRoute: FutureRoute,
  SettingsRoute: SettingsRoute,
  AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
